### ISSUE TITLE
Help with getting props correct

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/assemble-curation-functions#7]
Having tons of trouble turning the data structure you see in the attached screenshot into a typescript type. Any help would be hugely appreciated so I don't burn anymore time on this

<img width="523" alt="Screen Shot 2022-10-02 at 3 38 10 AM" src="https://user-images.githubusercontent.com/93691906/193450092-fb66d58f-fcd4-4591-a52a-af58b31fae1d.png">

cc: @dblodorn

**Comment by 0xTranqui** [comment]
for more context, I was able to pass that "theListing" value into the args for the new "addListings" call which takes in an array of Listing structs. couldnt figure out propifying it for the life of me smh

**Comment by salieflewis** [comment]
I think an array of listing structs just boils down to an array of arrays.

`listing?: string | string[] | any[] | [string, number, boolean][];`

I tried to test this but am still having trouble with my version of the curator factory and I don't own a curation pass of the curator contract you deployed.

**Comment by 0xTranqui** [comment]
@salieflewis this worked !!!! thank you so much. unbblocked me, should have rest of this package updated + pushed soon
